package com.portfolio.helpdesk.activity;

public enum ActivityEventType {
    CHAMADO_CRIADO,
    CHAMADO_EDITADO,
    ANALISTA_ATRIBUIDO,
    STATUS_ALTERADO,
    PRIORIDADE_ALTERADA,
    CATEGORIA_ALTERADA,
    COMENTARIO_ADICIONADO,
    COMENTARIO_EDITADO,
    COMENTARIO_REMOVIDO,
    ANEXO_ENVIADO,
    CHAMADO_REABERTO,
    CHAMADO_RESOLVIDO,
    CHAMADO_CANCELADO,
    USUARIO_CRIADO,
    USUARIO_EDITADO,
    USUARIO_ATIVADO,
    USUARIO_DESATIVADO,
    LOGIN_REALIZADO,
    LOGOUT_REALIZADO,
    SENHA_REDEFINIDA
}
